lecture-06-function-approximation.html: lecture-06-function-approximation.md function-approximation-theme.css
	marp $< \
	  --theme function-approximation-theme.css \
	  --allow-local-files \
	  --html \
	  --output $@
